# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagement', '0002_testrun_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(b'UNEXECUTED', b'UNEXECUTED'), (b'PASSED', b'PASSED'), (b'FAILED', b'FAILED'), (b'BLOCKED', b'BLOCKED')], default=0),
        ),
    ]
