# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmanagement', '0004_auto_20161122_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNEXECUTED'), (1, 'PASSED'), (2, 'FAILED'), (3, 'BLOCKED')], default=0),
        ),
    ]
